name: Cypress Tests
on:
  push:
    branches:
      - dev
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  trigger_backend_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Trigger Backend Build
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/Kvantikko/workout-log-backend/actions/workflows/8697446397/dispatches
          owner: Kvantikko
          repo: workout-log-backend
          workflow_id: 8697446397
          token: ${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
