name: Cypress Tests
on:
  push:
    branches:
      - dev
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  e2e-tests:
    env:
      DB_URL_TEST: 'localhost:34837/test'
      DB_USER_TEST: "ci"
      DB_PASSWORD_TEST: "sw0rdfish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout frontend repo
        run: npm ci

      - name: Vite build
        run: npm run build &

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: Kvantikko/workout-log-backend
          ref: dev
          token: ${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}
          path: "workout-log-backend"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ci
          password: sw0rdfish
          database: test
          port: 34837
          id: postgres

      - name: Build Spring Boot App with Maven
        run: mvn clean -Dspring-boot.run.profiles=test
        working-directory: workout-log-backend

      - name: Start Spring Boot App
        run: mvn spring-boot:run -Dspring-boot.run.profiles=test &
        working-directory: workout-log-backend

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Check if application is running
        run: |
          if netstat -tuln | grep -q 8080; then
            echo "Application is running on port 8080"
          else
            echo "Application is not running on port 8080"
          exit 1
          fi

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://localhost:8080/api/v1/auth/authenticate

      - name: Install serve
        run: npm install -g serve

      - name: Start Vite Build
        run: npx serve &
        working-directory: dist

      - name: Start Vite dev
        run: npm run dev

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome




