name: Cypress Tests
on:
  push:
    branches:
      - dev
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  e2e:
    env:
      DB_URL_TEST: 'localhost:34837/test'
      DB_USER_TEST: "ci"
      DB_PASSWORD_TEST: "sw0rdfish"
    runs-on: ubuntu-latest

    steps:
      

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: Kvantikko/workout-log-backend
          token: ${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}
          path: "workout-log-backend"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ci
          password: sw0rdfish
          database: test
          port: 34837
          id: postgres

      - name: List contents of workout-log-backend directory
        run: ls -la workout-log-backend

      - name: Check for pom.xml file
        run: test -f workout-log-backend/pom.xml && echo "pom.xml found" || echo "pom.xml not found"

      - name: Echo current path/location
        run: pwd

      - name: List contents 
        run: ls -la

      - name: Change directory to workout-log-backend
        run: cd workout-log-backend

      - name: Echo current path/location
        run: pwd

      - name: List contents 
        run: ls -la


  

      - name: Build with Maven
        run: mvn clean verify "-Dspring.profiles.active=test"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome




