name: Cypress Tests
on:
  push:
    branches:
      - dev
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: "Checkout backend repo"
        uses: actions/checkout@v4
        with:
          repository: Kvantikko/workout-log
          token: ${{ secrets.BACKEND_REPO_ACCESS_TOKEN }}
          path: "workout-log"

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
